// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: service.proto

package proto

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Secret struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" redis:"id"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" redis:"name"`
	Credentials          *Credentials     `protobuf:"bytes,3,opt,name=credentials,proto3" json:"-"`
	Text                 *Text            `protobuf:"bytes,4,opt,name=text,proto3" json:"-"`
	Binary               *Binary          `protobuf:"bytes,5,opt,name=binary,proto3" json:"-"`
	BankCard             *BankCard        `protobuf:"bytes,6,opt,name=bank_card,json=bankCard,proto3" json:"-"`
	Metadata             string           `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty" redis:"metadata"`
	CreateDt             *types.Timestamp `protobuf:"bytes,8,opt,name=create_dt,json=createDt,proto3" json:"create_dt,omitempty" redis:"create_dt"`
	UpdateDt             *types.Timestamp `protobuf:"bytes,9,opt,name=update_dt,json=updateDt,proto3" json:"update_dt,omitempty" redis:"update_dt"`
	IsDeleted            bool             `protobuf:"varint,10,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Secret) Reset()         { *m = Secret{} }
func (m *Secret) String() string { return proto.CompactTextString(m) }
func (*Secret) ProtoMessage()    {}
func (*Secret) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}
func (m *Secret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Secret.Unmarshal(m, b)
}
func (m *Secret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Secret.Marshal(b, m, deterministic)
}
func (m *Secret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Secret.Merge(m, src)
}
func (m *Secret) XXX_Size() int {
	return xxx_messageInfo_Secret.Size(m)
}
func (m *Secret) XXX_DiscardUnknown() {
	xxx_messageInfo_Secret.DiscardUnknown(m)
}

var xxx_messageInfo_Secret proto.InternalMessageInfo

func (m *Secret) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Secret) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Secret) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *Secret) GetText() *Text {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *Secret) GetBinary() *Binary {
	if m != nil {
		return m.Binary
	}
	return nil
}

func (m *Secret) GetBankCard() *BankCard {
	if m != nil {
		return m.BankCard
	}
	return nil
}

func (m *Secret) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

func (m *Secret) GetCreateDt() *types.Timestamp {
	if m != nil {
		return m.CreateDt
	}
	return nil
}

func (m *Secret) GetUpdateDt() *types.Timestamp {
	if m != nil {
		return m.UpdateDt
	}
	return nil
}

func (m *Secret) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

type Credentials struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty" redis:"login"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty" redis:"password"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}
func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (m *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(m, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Text struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty" redis:"data"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Text) Reset()         { *m = Text{} }
func (m *Text) String() string { return proto.CompactTextString(m) }
func (*Text) ProtoMessage()    {}
func (*Text) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}
func (m *Text) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Text.Unmarshal(m, b)
}
func (m *Text) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Text.Marshal(b, m, deterministic)
}
func (m *Text) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Text.Merge(m, src)
}
func (m *Text) XXX_Size() int {
	return xxx_messageInfo_Text.Size(m)
}
func (m *Text) XXX_DiscardUnknown() {
	xxx_messageInfo_Text.DiscardUnknown(m)
}

var xxx_messageInfo_Text proto.InternalMessageInfo

func (m *Text) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Binary struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty" redis:"data"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Binary) Reset()         { *m = Binary{} }
func (m *Binary) String() string { return proto.CompactTextString(m) }
func (*Binary) ProtoMessage()    {}
func (*Binary) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}
func (m *Binary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Binary.Unmarshal(m, b)
}
func (m *Binary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Binary.Marshal(b, m, deterministic)
}
func (m *Binary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Binary.Merge(m, src)
}
func (m *Binary) XXX_Size() int {
	return xxx_messageInfo_Binary.Size(m)
}
func (m *Binary) XXX_DiscardUnknown() {
	xxx_messageInfo_Binary.DiscardUnknown(m)
}

var xxx_messageInfo_Binary proto.InternalMessageInfo

func (m *Binary) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type BankCard struct {
	Number               string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty" redis:"number"`
	ExpirationDate       string   `protobuf:"bytes,2,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty" redis:"expiration_date"`
	HolderName           string   `protobuf:"bytes,3,opt,name=holder_name,json=holderName,proto3" json:"holder_name,omitempty" redis:"holder_name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BankCard) Reset()         { *m = BankCard{} }
func (m *BankCard) String() string { return proto.CompactTextString(m) }
func (*BankCard) ProtoMessage()    {}
func (*BankCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}
func (m *BankCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankCard.Unmarshal(m, b)
}
func (m *BankCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankCard.Marshal(b, m, deterministic)
}
func (m *BankCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankCard.Merge(m, src)
}
func (m *BankCard) XXX_Size() int {
	return xxx_messageInfo_BankCard.Size(m)
}
func (m *BankCard) XXX_DiscardUnknown() {
	xxx_messageInfo_BankCard.DiscardUnknown(m)
}

var xxx_messageInfo_BankCard proto.InternalMessageInfo

func (m *BankCard) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *BankCard) GetExpirationDate() string {
	if m != nil {
		return m.ExpirationDate
	}
	return ""
}

func (m *BankCard) GetHolderName() string {
	if m != nil {
		return m.HolderName
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Connect struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Active               bool     `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Connect) Reset()         { *m = Connect{} }
func (m *Connect) String() string { return proto.CompactTextString(m) }
func (*Connect) ProtoMessage()    {}
func (*Connect) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}
func (m *Connect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connect.Unmarshal(m, b)
}
func (m *Connect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connect.Marshal(b, m, deterministic)
}
func (m *Connect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connect.Merge(m, src)
}
func (m *Connect) XXX_Size() int {
	return xxx_messageInfo_Connect.Size(m)
}
func (m *Connect) XXX_DiscardUnknown() {
	xxx_messageInfo_Connect.DiscardUnknown(m)
}

var xxx_messageInfo_Connect proto.InternalMessageInfo

func (m *Connect) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Connect) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type Close struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Close) Reset()         { *m = Close{} }
func (m *Close) String() string { return proto.CompactTextString(m) }
func (*Close) ProtoMessage()    {}
func (*Close) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}
func (m *Close) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Close.Unmarshal(m, b)
}
func (m *Close) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Close.Marshal(b, m, deterministic)
}
func (m *Close) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Close.Merge(m, src)
}
func (m *Close) XXX_Size() int {
	return xxx_messageInfo_Close.Size(m)
}
func (m *Close) XXX_DiscardUnknown() {
	xxx_messageInfo_Close.DiscardUnknown(m)
}

var xxx_messageInfo_Close proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Secret)(nil), "Secret")
	proto.RegisterType((*Credentials)(nil), "Credentials")
	proto.RegisterType((*Text)(nil), "Text")
	proto.RegisterType((*Binary)(nil), "Binary")
	proto.RegisterType((*BankCard)(nil), "BankCard")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*Connect)(nil), "Connect")
	proto.RegisterType((*Close)(nil), "Close")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 644 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xdf, 0x6e, 0xd3, 0x3e,
	0x14, 0xc7, 0x95, 0xad, 0x4d, 0xd3, 0xd3, 0xae, 0xdb, 0xfc, 0xfb, 0xb3, 0x50, 0x04, 0xa9, 0x0c,
	0x82, 0x69, 0x62, 0xde, 0x34, 0x84, 0x84, 0x10, 0x57, 0x6d, 0xaf, 0x77, 0xe1, 0x0d, 0x90, 0xb8,
	0xa9, 0xdc, 0xd8, 0x74, 0xd6, 0x92, 0xb8, 0x72, 0xdc, 0x31, 0x5e, 0x8c, 0xc7, 0xc9, 0x03, 0x70,
	0x83, 0x94, 0x27, 0x40, 0x71, 0x9c, 0xb6, 0x80, 0xb8, 0xe0, 0x2a, 0x39, 0xe7, 0xfb, 0xf1, 0xd7,
	0xf2, 0xf1, 0x39, 0x86, 0xbd, 0x5c, 0xe8, 0x3b, 0x19, 0x0b, 0xb2, 0xd4, 0xca, 0xa8, 0xe1, 0xe9,
	0x42, 0x9a, 0x9b, 0xd5, 0x9c, 0xc4, 0x2a, 0x3d, 0x5b, 0xa8, 0x85, 0x3a, 0xb3, 0xe9, 0xf9, 0xea,
	0x93, 0x8d, 0x6c, 0x60, 0xff, 0x1c, 0x1e, 0x2d, 0x94, 0x5a, 0x24, 0x62, 0x43, 0x19, 0x99, 0x8a,
	0xdc, 0xb0, 0x74, 0x59, 0x03, 0xf8, 0xfb, 0x2e, 0xf8, 0x57, 0x22, 0xd6, 0xc2, 0xa0, 0xc7, 0xb0,
	0x23, 0x79, 0xe8, 0x8d, 0xbc, 0xe3, 0xee, 0x78, 0x50, 0x16, 0x11, 0x68, 0xc1, 0x65, 0xfe, 0x06,
	0x4b, 0x8e, 0xe9, 0x8e, 0xe4, 0xe8, 0x29, 0xb4, 0x32, 0x96, 0x8a, 0x70, 0xc7, 0x12, 0x07, 0x65,
	0x11, 0xf5, 0x1d, 0x51, 0xa5, 0x31, 0xb5, 0x2a, 0x7a, 0x05, 0xbd, 0x58, 0x0b, 0x2e, 0x32, 0x23,
	0x59, 0x92, 0x87, 0xbb, 0x23, 0xef, 0xb8, 0x77, 0xd1, 0x27, 0x93, 0x4d, 0x6e, 0xdc, 0xfe, 0x56,
	0x44, 0xde, 0x29, 0xdd, 0xe6, 0xd0, 0x08, 0x5a, 0x46, 0xdc, 0x9b, 0xb0, 0x65, 0xf9, 0x36, 0xb9,
	0x16, 0xf7, 0xa6, 0x01, 0xad, 0x82, 0x9e, 0x81, 0x3f, 0x97, 0x19, 0xd3, 0x5f, 0xc2, 0xb6, 0x65,
	0x3a, 0x64, 0x6c, 0xc3, 0x86, 0x72, 0x2a, 0x3a, 0x85, 0xee, 0x9c, 0x65, 0xb7, 0xb3, 0x98, 0x69,
	0x1e, 0xfa, 0x16, 0xed, 0x92, 0x31, 0xcb, 0x6e, 0x27, 0x4c, 0xf3, 0x06, 0x0e, 0xe6, 0x2e, 0x81,
	0xce, 0x21, 0x48, 0x85, 0x61, 0x9c, 0x19, 0x16, 0x76, 0xec, 0xc9, 0xfe, 0x2d, 0x8b, 0xe8, 0xc0,
	0x9d, 0xac, 0x91, 0x30, 0x5d, 0x53, 0xe8, 0x12, 0xba, 0xb1, 0x16, 0xcc, 0x88, 0x19, 0x37, 0x61,
	0x60, 0x37, 0x18, 0x92, 0xba, 0xce, 0xa4, 0xa9, 0x33, 0xb9, 0x6e, 0xea, 0x3c, 0xfe, 0xaf, 0x2c,
	0xa2, 0x43, 0x67, 0xb7, 0x5e, 0x87, 0x69, 0x50, 0xff, 0x4f, 0x4d, 0xe5, 0xb7, 0x5a, 0x72, 0xe7,
	0xd7, 0xfd, 0x2b, 0xbf, 0xf5, 0x3a, 0x4c, 0x83, 0xfa, 0x7f, 0x6a, 0xd0, 0x23, 0x00, 0x99, 0xcf,
	0xb8, 0x48, 0x84, 0x11, 0x3c, 0x84, 0x91, 0x77, 0x1c, 0xd0, 0xae, 0xcc, 0xa7, 0x75, 0x02, 0xdf,
	0x40, 0x6f, 0xeb, 0x32, 0xd0, 0x73, 0x68, 0x27, 0x6a, 0x21, 0x33, 0x77, 0xf1, 0x87, 0x65, 0x11,
	0xed, 0x39, 0x77, 0x9b, 0xc7, 0xb4, 0xd6, 0xab, 0x42, 0x2d, 0x59, 0x9e, 0x7f, 0x56, 0x9a, 0xbb,
	0x16, 0xd8, 0x2e, 0x54, 0x23, 0x61, 0xba, 0xa6, 0xf0, 0x0b, 0x68, 0x55, 0xd7, 0x58, 0x35, 0x8e,
	0x2d, 0xaf, 0xf7, 0x5b, 0xe3, 0xd4, 0xa5, 0xb5, 0x2a, 0x26, 0xe0, 0xd7, 0x17, 0xfa, 0x13, 0xdf,
	0xff, 0x23, 0xff, 0xd5, 0x83, 0xa0, 0xb9, 0x56, 0x74, 0x02, 0x7e, 0xb6, 0x4a, 0xe7, 0x42, 0xbb,
	0x4d, 0x50, 0x59, 0x44, 0x83, 0xa6, 0x3b, 0xad, 0x80, 0xa9, 0x23, 0xd0, 0x14, 0xf6, 0xc5, 0xfd,
	0x52, 0x6a, 0x66, 0xa4, 0xca, 0x66, 0x55, 0xd1, 0xdc, 0x79, 0x1e, 0x96, 0x45, 0x74, 0xe4, 0x16,
	0xfd, 0x42, 0x60, 0x3a, 0xd8, 0x64, 0xa6, 0xcc, 0x08, 0xf4, 0x1a, 0x7a, 0x37, 0x2a, 0xe1, 0x42,
	0xcf, 0xec, 0x50, 0xec, 0x5a, 0x87, 0xa3, 0xb2, 0x88, 0xfe, 0x71, 0x0e, 0x5b, 0x2a, 0xa6, 0x50,
	0x47, 0x97, 0x55, 0x70, 0x02, 0xad, 0x77, 0xb9, 0xd0, 0x68, 0xb0, 0x99, 0x37, 0x3b, 0x5f, 0x68,
	0x7b, 0xbe, 0xea, 0x69, 0xc2, 0x6f, 0xa1, 0x33, 0x51, 0x59, 0x26, 0x62, 0x83, 0x1e, 0x40, 0x6b,
	0x95, 0xbb, 0x03, 0x56, 0x13, 0x52, 0x79, 0x50, 0x9b, 0x42, 0xff, 0x83, 0xcf, 0x62, 0x23, 0xef,
	0xea, 0xb5, 0x01, 0x75, 0x11, 0xee, 0x40, 0x7b, 0x92, 0xa8, 0x5c, 0x5c, 0x7c, 0x80, 0xfe, 0x7b,
	0xb6, 0x4a, 0xcc, 0x55, 0xfd, 0x96, 0xa0, 0x27, 0xd0, 0x9f, 0xd8, 0xf6, 0xbb, 0x32, 0x5a, 0xb0,
	0x14, 0x05, 0xc4, 0xed, 0x32, 0xec, 0x90, 0xfa, 0x35, 0x38, 0xf7, 0x10, 0x86, 0xfd, 0xb1, 0x56,
	0x8c, 0xc7, 0x2c, 0x37, 0xee, 0x89, 0x68, 0xd4, 0xa1, 0x4f, 0xac, 0xf1, 0x18, 0x3e, 0x06, 0x84,
	0xb8, 0xd7, 0xc5, 0xb7, 0x9f, 0x97, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4e, 0xff, 0xaf, 0x84,
	0xb2, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VaultServiceClient is the client API for VaultService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VaultServiceClient interface {
	CreateStream(ctx context.Context, in *Connect, opts ...grpc.CallOption) (VaultService_CreateStreamClient, error)
	BroadcastSecret(ctx context.Context, in *Secret, opts ...grpc.CallOption) (*Close, error)
}

type vaultServiceClient struct {
	cc *grpc.ClientConn
}

func NewVaultServiceClient(cc *grpc.ClientConn) VaultServiceClient {
	return &vaultServiceClient{cc}
}

func (c *vaultServiceClient) CreateStream(ctx context.Context, in *Connect, opts ...grpc.CallOption) (VaultService_CreateStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_VaultService_serviceDesc.Streams[0], "/VaultService/CreateStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &vaultServiceCreateStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VaultService_CreateStreamClient interface {
	Recv() (*Secret, error)
	grpc.ClientStream
}

type vaultServiceCreateStreamClient struct {
	grpc.ClientStream
}

func (x *vaultServiceCreateStreamClient) Recv() (*Secret, error) {
	m := new(Secret)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vaultServiceClient) BroadcastSecret(ctx context.Context, in *Secret, opts ...grpc.CallOption) (*Close, error) {
	out := new(Close)
	err := c.cc.Invoke(ctx, "/VaultService/BroadcastSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VaultServiceServer is the server API for VaultService service.
type VaultServiceServer interface {
	CreateStream(*Connect, VaultService_CreateStreamServer) error
	BroadcastSecret(context.Context, *Secret) (*Close, error)
}

// UnimplementedVaultServiceServer can be embedded to have forward compatible implementations.
type UnimplementedVaultServiceServer struct {
}

func (*UnimplementedVaultServiceServer) CreateStream(req *Connect, srv VaultService_CreateStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateStream not implemented")
}
func (*UnimplementedVaultServiceServer) BroadcastSecret(ctx context.Context, req *Secret) (*Close, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastSecret not implemented")
}

func RegisterVaultServiceServer(s *grpc.Server, srv VaultServiceServer) {
	s.RegisterService(&_VaultService_serviceDesc, srv)
}

func _VaultService_CreateStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Connect)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VaultServiceServer).CreateStream(m, &vaultServiceCreateStreamServer{stream})
}

type VaultService_CreateStreamServer interface {
	Send(*Secret) error
	grpc.ServerStream
}

type vaultServiceCreateStreamServer struct {
	grpc.ServerStream
}

func (x *vaultServiceCreateStreamServer) Send(m *Secret) error {
	return x.ServerStream.SendMsg(m)
}

func _VaultService_BroadcastSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Secret)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).BroadcastSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VaultService/BroadcastSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).BroadcastSecret(ctx, req.(*Secret))
	}
	return interceptor(ctx, in, info, handler)
}

var _VaultService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "VaultService",
	HandlerType: (*VaultServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BroadcastSecret",
			Handler:    _VaultService_BroadcastSecret_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateStream",
			Handler:       _VaultService_CreateStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
